export const COMPOSER_EDITOR_MIN_HEIGHT = 32;
export const COMPOSER_EDITOR_EXPANDED_MIN_HEIGHT = 72;
export const COMPOSER_EDITOR_MAX_HEIGHT = 160;
export const COMPOSER_EDITOR_PADDING_HORIZONTAL = 4;
export const COMPOSER_EDITOR_EXPANDED_PADDING_VERTICAL = 4;
export const COMPOSER_ACTION_BUTTON_SIZE = 32;
export const COMPOSER_SURFACE_BORDER_WIDTH = 1;
export const COMPOSER_PILL_RADIUS = 24;
export const COMPOSER_PILL_PADDING_HORIZONTAL = 12;
export const COMPOSER_PILL_PADDING_VERTICAL = 8;
export const COMPOSER_PILL_EXPANDED_PADDING_TOP = 14;
export const COMPOSER_STRIP_OVERLAP = 16;
export const COMPOSER_STRIP_INSET = 22;
export const COMPOSER_STRIP_RADIUS = 16;
export const COMPOSER_STRIP_PADDING_TOP = COMPOSER_STRIP_OVERLAP + 4;
export const COMPOSER_STRIP_PADDING_BOTTOM = 4;
export const COMPOSER_STRIP_PADDING_START = 4;
export const COMPOSER_STRIP_PADDING_END = 8;
export const COMPOSER_STRIP_ROW_HEIGHT = 36;
export const COMPOSER_DOCK_COLLAPSED_PADDING_VERTICAL = 6;
export const COMPOSER_DOCK_EXPANDED_PADDING_VERTICAL = 8;

const COMPOSER_COLLAPSED_EDITOR_ROW_HEIGHT = Math.max(
  COMPOSER_EDITOR_MIN_HEIGHT,
  COMPOSER_ACTION_BUTTON_SIZE,
);

export const COMPOSER_STRIP_VISIBLE_HEIGHT =
  COMPOSER_STRIP_PADDING_TOP +
  COMPOSER_STRIP_ROW_HEIGHT +
  COMPOSER_STRIP_PADDING_BOTTOM +
  COMPOSER_SURFACE_BORDER_WIDTH -
  COMPOSER_STRIP_OVERLAP;

export const COMPOSER_COLLAPSED_CHROME =
  COMPOSER_DOCK_COLLAPSED_PADDING_VERTICAL * 2 +
  COMPOSER_SURFACE_BORDER_WIDTH * 2 +
  COMPOSER_PILL_PADDING_VERTICAL * 2 +
  COMPOSER_COLLAPSED_EDITOR_ROW_HEIGHT +
  COMPOSER_STRIP_VISIBLE_HEIGHT;

export const COMPOSER_EXPANDED_CHROME =
  COMPOSER_DOCK_EXPANDED_PADDING_VERTICAL * 2 +
  COMPOSER_SURFACE_BORDER_WIDTH * 2 +
  COMPOSER_PILL_EXPANDED_PADDING_TOP +
  COMPOSER_EDITOR_EXPANDED_MIN_HEIGHT +
  COMPOSER_PILL_PADDING_VERTICAL +
  COMPOSER_STRIP_VISIBLE_HEIGHT;

export function composerDockPaddingVertical(isExpanded: boolean): number {
  return isExpanded
    ? COMPOSER_DOCK_EXPANDED_PADDING_VERTICAL
    : COMPOSER_DOCK_COLLAPSED_PADDING_VERTICAL;
}

export function composerEditorVerticalPadding(isExpanded: boolean, lineHeight: number): number {
  if (isExpanded) return COMPOSER_EDITOR_EXPANDED_PADDING_VERTICAL;
  return Math.max(0, Math.floor((COMPOSER_EDITOR_MIN_HEIGHT - lineHeight) / 2));
}
