// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 't3-chat-light', 't3-chat-dark', 'grove-light', 'grove-dark', 'ocean-light', 'ocean-dark', 'ember-light', 'ember-dark', 'iris-light', 'iris-dark', 'gruvbox-light', 'gruvbox-dark', 'default-light', 'default-dark', 'catppuccin-light', 'catppuccin-dark', 'one-dark-pro-light', 'one-dark-pro-dark', 'cobalt2-light', 'cobalt2-dark']
    }
}

export {}
